### PR TITLE
Poem filtering prototype

### PR DESCRIPTION
**Pull request by kufii**
I made this prototype for filtering and sorting the poem list.

I added filters by kimariji lengh and verse 2 length, and you can sort by poem number, kimariji length, and verse 2 length.

Like I said this is just a prototype so let me know if you have any opinions on UI/UX, or if the code isn't up to your standards. I tried my best, but I've never used Ember before, so there definitely could be some areas of improvement.

### CODE REVIEW

**Comment by GoldenChrysus** [comment]
Thanks for taking the initiative on that. In the future -- and nothing personal -- I would prefer if we coordinate on a spec for new features prior to developing them. How you envision a feature may be different from how I envision it, and it is more inline with the development process I am accustomed to using daily at work.

----

For the most part, I like the change. For the UI, I was looking to implement something that distinctly separated the filters from the poem grid. For example, like putting it in this message container:
image

The padding would have to be fixed on that because the left/right padding is greater than the top/bottom padding.

----

Also, as you can see in that picture, the dropdowns are lacking down arrows. I'm not sure if that's a dropdown instantiation issue (unfortunately, the Semantic Ember package is far too out of date to work in this version of Ember, so the Semantic components have to be instantiated in Ember unless new Ember components are made, which I don't feel like doing). Although it looks like you are instantiating, so not sure where this issue stems from.

e.g. a regular Semantic dropdown:
image

I didn't realize these were dropdowns at first due to the missing arrows. I thought they would be text inputs until I clicked one.

----

Probably related, when you clear a dropdown, the clear x persists (in Semantic, the x gets replaced by the aforementioned missing dropdown arrow):
image

And the x is oddly out of position.

e.g. a regular Semantic clearable dropdown:
image

My initial guess for these dropdown issues is that you're assigning the class `clearable`, but Semantic documentation shows their dropdowns without this class and `clearable` is assigned via the instantiation options: https://fomantic-ui.com/modules/dropdown.html#/examples

----

In the second verse answer length dropdown, the 6 option needs to be removed. There are no poems with a second verse answer length of 6. This should match the statistics in the review index:
image

----

I'd also like to shrink the dropdowns to the minimum necessary width. Semantic dropdowns have a `compact` variant that does this. These dropdowns currently take up more space than they need to, and I'd like to use some of that space for other filters like actually typing out the hiragana in a poem or adding learned/unlearned filters (per your issue #4).
image

----

As for the code...a lot of it doesn't follow the guidelines I provided previously: https://github.com/GoldenChrysus/ffxiv-ember-overlay#contributing I understand if the .editorconfig is not setup properly, but ultimately these guidelines must be followed. There are numerous issues, so I'll point out a few:

Control blocks need braces and the inner logic needs to be on a new line; essentially, a full control block, not a shorthand one.
`if (diff !== 0) return diff;`

Quoting must be in double-quotes unless using backticks to interpolate (or use backticks in order to enclose a string that contains double quotes itself and you don't want to escape).
`@tracked sort = 'num';`

Prefer members that are instantiated be separated by a blank line from those that are uninstantiated.
```
	@tracked sort = 'num';
	@tracked kimariji_length;
	@tracked verse2_length;
```

Same issue here with control blocks. Additionally, discrete blocks of code (e.g. control blocks) should be separated by a blank line before and after the block, unless it doesn't make sense to (e.g. your control block is at the end of a method and it doesn't make sense to have an arbitrary blank line after it). Also looks like, after pasting it into this comment, that there is space indentation here.
```
		if (this.kimariji_length)
			poems = poems.filter(p => [...p.kimariji].length === this.kimariji_length);
		if (this.verse2_length)
		  poems = poems.filter(p => [...p.second_verse_answer].length === this.verse2_length);
```

Variable assignments should be aligned.
```
		this.sort = sort;
		this.kimariji_length = kimariji_length;
		this.verse2_length = verse2_length;
```

Code seems to have been needlessly changed:
```
-				return "eight wide widescreen eight wide large screen eight wide computer eight wide tablet sixteen wide mobile column";
+				return 'eight wide widescreen eight wide large screen eight wide computer eight wide tablet sixteen wide mobile column';
```

And this is kind of a matter of preference...but these ternary hurt my head to look at. e.g:
```
this.sort === 'kimariji'
	? [...p.kimariji].length
	: this.sort === 'verse2'
	? [...p.second_verse_answer].length
	: 0,
```

I personally write these like:
```
(this.sort === "kimariji")
	? [...p.kimariji].length
	: ((this.sort === "verse2")
		? [...p.second_verse_answer].length
		: 0),
```

And maybe that hurts your head to look at. I'll just lose sleep at night if unnested (non-nested?) ternaries are in the code.

They also seem a little inconsistent. For example, this comparison ternary actually uses some kind of nesting, I think, after your `cb.desc` goes into the first `isString(aa)` which has its logic nested, but the second `isString(aa)` doesn't have its logic nested in the same way. It just...hurts my brain, to be honest.

----

As you could probably tell from my previous example, I also like Boolean comparisons to be enclosed in parenths:
e.g. `this.sort === 'kimariji'` vs `(this.sort === 'kimariji')`

----

Note necessarily a code concern, but more of a question. Is there any reason the `poems` property was turned into a computed property?
```
-	poems = this.args.poems || [];
+	get poems() {
+		return this.args.poems || [];
+	}
```

The computed properties in Glimmer components get automatically tracked, if that was what you were going for, but this isn't really a computed property (the original is actually the Ember-provided example of how to set a default value for a property). But you can still use the @tracked decorator on these, so wondering if there was some issue tracking it (I actually have tons of issues with tracking since this was built on a pre-release, non-official Octane blueprint, which is why you'll notice many of the components use `Component.extend({})` rather than true class extensions).

----

And the last thing. Probably kind of annoying. I'd prefer if the `verse2` items were instead called `second_verse` or `second_verse_answer_length` where applicable. It's a lot to type out, but the majority of the other code (if I'm recalling correctly) uses `second_verse_*` for naming. And usually `second_verse_answer_*` because _technically_ most of the code deals with the _answer_ of the second verse rather than the second verse in its entirety (which is what `verse2` or `second_verse` imply).

**Comment by kufii** [comment]
Sorry about that! Like i said it was just a prototype I made quickly so I wouldn't be offended if you just straight up rejected if you didn't like the design. With that said I will discuss with you first if I do something like this in the future. Will take a look at these comments when I have some free time later

**Comment by GoldenChrysus** [comment]
Nah it's unlikely I would ever outright rejects someone's code. If you lay down a decent foundation for a feature, it makes sense to iterate on it with changes/improvements rather than just rejecting someone's effort.

**Comment by kufii** [comment]
I made changes according to your comments. Do you have any opinion on how to improve the UI for mobile widths? I don't think it looks very good but I'm not sure what to do about it

**Comment by kufii** [comment]
made adjustments according to your code style.

As for using the computed property in the grid, when not using the computed property the grid does not  seem to update when the filters change.

**Comment by GoldenChrysus** [comment]
Can you pull latest master? I added testing and linting -- the linting isn't perfect but a good start for verifying the coding style. Also caused a conflict for you when adding the template linting; sorry about that.

I'll check out the mobile version later tonight to see what can be done.

**Comment by kufii** [comment]
Awesome! glad to have good linting, helps a lot. I've fixed all the linter errors

**Comment by GoldenChrysus** [comment]
Looking great. Can the header items in the dropdowns be removed? Seems redundant.

So for mobile...I'm thinking the filters could be hidden by default and they'll become stacked/`fluid` dropdowns (so each dropdown takes up the full width of the message container). Then some sort of clickable link with a down arrow to indicate that it will reveal content; when clicked the filters will slide out to be revealed (and slide up when clicked again, so a toggle).

Very quick/bad mockup:
image

Needs some padding and alignment work but probably a fairly clean way to display them short of doing something ridiculous like having the filters slide out in the existing mobile sidebar.

Of course, the filters would continue to display by default on table and up, and the filter show/hide toggle.

**Comment by GoldenChrysus** [comment]
Oh also, what is this? Do the changes not track properly if you don't run them in the timeout?

```
		setTimeout(() => {
			this.sort                       = sort;
			this.kimariji_length            = kimariji_length;
			this.second_verse_answer_length = second_verse_answer_length;
		}, 0);
```

**Comment by kufii** [comment]
The set timeout is not needed for functionality, bit it makes it feel more responsive. otherwise the ui is blocked until the poem grid is redrawn, making it kinda feel like it freezes when you change the dropdown. I found it just was a better UX with the settimeout personally.

**Comment by kufii** [comment]
Also for the headers in the dropdown, I added them so you could tell what the dropdown was for even after selecting an item (since after you select something the placeholder text goes away and there's no indicator for what the dropdown is for). I'm fine with removing if you don't want it but do you think this is a valid reason to keep it?

**Comment by kufii** [comment]
I tried putting the filters in an accordion and I think it looks pretty good. What do you think?

**Comment by kufii** [comment]
Made the requested changes and added the test cases

**Pull request merged**
