### PR TITLE
2 column lesson layout for tablets

### LINKED ISSUE #5: cards too big at tablet width for lessons
image

This makes it not as nice as it could be to use on my tablet. I was messing around and at tablet sizes, the 2 column layout still looks really good

### PR DESCRIPTION
**Pull request by kufii**
Fixes #5

### CODE REVIEW

**Comment by kufii** [comment]
btw the gitattributes change was because since I'm using Windows, git was detecting some line ending changes that shouldn't be committed.

**Comment by kufii** [comment]
Screenshot of computer width:

image

Screenshot of tablet width:

image

Screenshot of phone width:

image

**Comment by GoldenChrysus** [comment]
Please only make the minimal code changes necessary to implement your desired result. You've moved _all_ stylings out of the `computerBreakpoint - 1` (table styling) into the `tabletBreakpoint - 1` (mobile styling), which causes issues on various screen sizes. For example, the demo card previously used font size `4.40vw` but now uses `4.50vw` because you've moved the relevant tablet styling from the tablet stylings into the mobile styling. Additionally, the mobile styling now uses `4.40vw` instead of the `8.50vw` it was set to previously. The _only_ change that should be present in `grabber-card.less` is your recalculation of the font size of the existing `.grabber-card-outer.standalone-lesson` item for the tablet styling. Your change is not for the other card types, so it is incorrect to have moved so many stylings not relevant to your change. I have attached various photos of the issues.

Text too large; the exact issue I mentioned would occur with the text flowing into what should be whitespace due to lack of proper font size calculation:
image

Same as above:
image

Text outright exiting the card:
image

Text far too small on mobile:
image

Please use the formula I provided; you will notice the number it provides for the tablet calculation is smaller than the number you used.

Also, all of the changes you made not relevant to this styling change need to be removed. If your editing environment is automatically modifying files, you either need to configure it to not do so or unstage the files before committing. e.g. all the .gitattributes changes need to go, and you've made several version changes in the API's Gemlock file. Same with the package-lock.json changes. There shouldn't be anything in this change that requires reversioning of dependencies or packages.

**Comment by GoldenChrysus** [comment]
Additionally (given your recent commit), like stated in the issue, please make a separate issue for reviews. I prefer 1 issue <-> 1 pull. This way, if something ever needs to be unmerged, I can selectively unmerge just the exact code needed for a change, rather than unmerging code that addresses multiple issues.

**Comment by kufii** [comment]
sure thing, will do, give me a bit to update everything

**Comment by kufii** [comment]
made updates according to your comments, using the formula you provided and the widths in the chrome inspector

**Comment by kufii** [comment]
thank's for your comments, my bad on the tabs, I was sure I had tab indentation set. You should probably update your .editorconfig settings so that the indentation is auto set correctly, but I'll fix this and re commit sometime tomorrow.

Are you sure you want the gitattribute changes removed? Just means there's a chance I could potentially commit line ending changes when I'm working on windows.

I'll remove the changes to the gemfile.

The change to the package.lock just fixed a vulnerability via `npm audit fix`. Are you sure you want this removed? If so no problem

**Comment by GoldenChrysus** [comment]
Everything not related to this change should be removed. A security vulnerability has no relation to a visual styling change. As mentioned, I prefer to keep changes as granular and minimal as possible so there is a direct relation between an issue and a pull that resolves said issue; rather than having pulls that resolve issues other than the described intent.

**Comment by kufii** [comment]
Understood, I'll remove them all

**Pull request merged**
